<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserProductionSeeder extends Seeder
{
    /**
     * Run the database seeds to sync all company employee accounts to production.
     */
    public function run(): void
    {
        $users = [
            [
                'id' => 1,
                'username' => 'admin',
                'full_name' => null,
                'email' => 'pbl.512hebat+admin@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$4qcT4EdmP168kvQYI2zlcuXBG643.bBaeXp//2zYp8f6Fxa2lxhAq',
                'role' => 'admin',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'qyeGzV85ua66frFtYXSbSBlLp11qNzDDRfgI0XK8cX2ROv7A6bqkhf0U0tFD',
                'created_at' => '2026-01-20 03:43:49',
                'updated_at' => '2026-08-27 10:38:43',
            ],
            [
                'id' => 7,
                'username' => 'TRINWETTY',
                'full_name' => 'Trinwetty',
                'email' => 'trinwetty@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$do8wc/k.O6ySopn0QrjqjO3sKA/NVvfs3Odlf57I7gsVa3MiNXpAm',
                'role' => 'Chief of Staff',
                'can_manage_cpt_contracts' => 1,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'dm7xmkqz7q5MEZpXQKcFP11mTOWkfKsl0W2AeWZ4cclGyANrtauqGUTwkdvE',
                'created_at' => '2026-03-06 02:27:29',
                'updated_at' => '2026-09-08 16:13:39',
            ],
            [
                'id' => 11,
                'username' => 'triminami',
                'full_name' => 'Tri Minarni',
                'email' => 'tri@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$B2mIylnyBjP.VFqhlYiBe.eQpUe1xGIs4RTQ5OujeIRuLgftqrPkS',
                'role' => 'Ka. BU Gas & SPBE',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => '5HhuS0fRjnus1PtZhutZkLabazvInCvbo8bkjWWoM7I51R34ZS3grN3aAC3z',
                'created_at' => '2026-03-10 03:17:39',
                'updated_at' => '2026-09-08 16:13:40',
            ],
            [
                'id' => 12,
                'username' => 'ekowati',
                'full_name' => 'Ekowati',
                'email' => 'ekowati@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$Z1j6slx1cuyBJ1aInEAuUuzy17Ji4ma8iRij3r.BfjrWdHhvPojqa',
                'role' => 'Chief F&A Gas',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'k0V5j1zwJM7cxGhL7SsdD4Fn8C6ZadUgRbpttWlPOcDRJYjJYInbBpJQfYQO',
                'created_at' => '2026-03-10 03:20:12',
                'updated_at' => '2026-09-08 16:13:40',
            ],
            [
                'id' => 13,
                'username' => 'ibnumirza',
                'full_name' => 'Ibnu Mirza',
                'email' => 'ibnumirza@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$ZPsJcL9LBdVo3iSLlgiicOi7xeI/lzhclzWXOIgZwVmuwXE1laJPC',
                'role' => 'Ka. Div Retail',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'OYD1oAdOtJEYm7nsJr3yxJGVfYpXcwnMY5xMAstKCsmQ9JJG0cwbrK8L46HT',
                'created_at' => '2026-03-10 03:20:57',
                'updated_at' => '2026-09-08 16:13:39',
            ],
            [
                'id' => 15,
                'username' => 'putrilarasati',
                'full_name' => 'Putri Larasati Ariandini',
                'email' => 'pbl.512hebat+putrilarasati@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$.WK4ykFQvSRnMANhkNrNjus3xX9pOO3jC3i6uepQtY20OBIbj5BuK',
                'role' => 'Ka. Div F&A',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'fCIH5SRANYES9t4CkTrVKAslRVzaO5mIvpO3QWF8C56gxp6awZThHIExRcFF',
                'created_at' => '2026-03-10 03:23:33',
                'updated_at' => '2026-08-27 10:38:43',
            ],
            [
                'id' => 16,
                'username' => 'suhaimi',
                'full_name' => 'Suhaimi',
                'email' => 'staff.audit@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$Q9M2b/OmMFnktmpK6xgn0.xTTtNmt4e77pi2OhsEiI4WJgpLumtOi',
                'role' => 'Dept. Internal Audit',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => '3MmZYvd1fOMO1Kr1ivJqOUZaWt0hagcQiQRhXCOZjevLkPDon5PukE5fzGOG',
                'created_at' => '2026-03-10 03:25:35',
                'updated_at' => '2026-09-08 16:13:40',
            ],
            [
                'id' => 17,
                'username' => 'zikri',
                'full_name' => 'Zikri',
                'email' => 'zikri@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$JVhONaOljq/6aBacBlqsNe/FVqFl9JYu2UK5qNY.qtP3eZCCQqpzi',
                'role' => 'Direktur Utama',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'DgjklFdjmD1FFFP3bRPkgs0A89kU5OS95GIx8cT77oxk7d5PpfI3JYFY2gVf',
                'created_at' => '2026-03-10 03:26:43',
                'updated_at' => '2026-09-08 16:13:39',
            ],
            [
                'id' => 26,
                'username' => 'YayuIndahMaya',
                'full_name' => 'Yayu Indah Maya',
                'email' => 'yayu@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$YRboiHw4MgvZcfKCE.yxvuYi7E/N1a98O3o5VxPPCnCbMngc.SP2u',
                'role' => 'Ka. BU CPT',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => '0bFgmw9d278j7XM9zONmRjYo889UwKNZ1inpwtrWfN55wlaSqBPITPeQmzY3',
                'created_at' => '2026-08-13 07:39:36',
                'updated_at' => '2026-09-08 16:13:42',
            ],
            [
                'id' => 28,
                'username' => 'imamm',
                'full_name' => 'IMAM M',
                'email' => 'pbl.512hebat+imamm@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$zRtpPI4AwnJzMShO.uJMkeWR5mM77eFWR8HyvivCNANLeFOCFrB0O',
                'role' => 'Ka. Dept. QMS',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'v3CerWmR6kEGFD1Xdy5vG4xRLcDMzglmE6gUKK7btBqNRFzn1SLEwgjORX5D',
                'created_at' => '2026-08-13 07:58:54',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 46,
                'username' => 'nazrikudsi',
                'full_name' => 'Nazri Kudsi',
                'email' => 'nazri@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$TASuVudzkg9CkQTgxTFx8.vKzY2iNlRg98wdbKZo.YhnJehWClC52',
                'role' => 'Ka. BU SPBU',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => '5baWkpDF2SHx8lAyhQBQWluWSrhdPgq02JJ061tZY7coXVUqE4O69ayZqRRy',
                'created_at' => '2026-08-14 07:31:45',
                'updated_at' => '2026-09-08 16:13:39',
            ],
            [
                'id' => 47,
                'username' => 'garioanora',
                'full_name' => 'Gario Anora Daya',
                'email' => 'gario@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$6mXqOVMGMwjZLhUu2v8y/eAIxjvYK2bdwM25yNwDrMdbiVaX294Pu',
                'role' => 'Chief F&A SPBU',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'yMaxc8gf7oG72Q2I5haUiXdFnv3r8fzF7bDoS6BnnT5sGIgBiRDn1SuVtI1y',
                'created_at' => '2026-08-14 07:31:45',
                'updated_at' => '2026-09-08 16:13:39',
            ],
            [
                'id' => 48,
                'username' => 'laluwandi',
                'full_name' => 'Lalu Wandi',
                'email' => 'wandi@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$PnqcFXG1zpIKPv95fU600eNcw9DZ1mbjykOxUsqR/UTI2LNva/RQm',
                'role' => 'Wa. Ka. Div Retail',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'twPrT6mRofwj9UwoSBznaVebkv6KRIQdN7DDbrY2LBwAM1kk6XQdpRumDbTu',
                'created_at' => '2026-08-14 07:31:45',
                'updated_at' => '2026-09-08 16:13:39',
            ],
            [
                'id' => 93,
                'username' => 'test_qms',
                'full_name' => 'Ka Dept QMS Test',
                'email' => 'pbl.512hebat+test_qms@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$cdBrOzaj8C/Bgx/z2LggUeDxwf/UMIFIM0La3RMp1t6V/T8diel4.',
                'role' => 'Ka. Dept. QMS',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-08-18 09:53:28',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 94,
                'username' => 'test_cos',
                'full_name' => 'Chief of Staff Test',
                'email' => 'pbl.512hebat+test_cos@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$95JEOG2BJ.TBH14RqT4p2O1.VeOM40ePQwE/ZyJ27WQutiGxYRijS',
                'role' => 'Chief of Staff',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-08-18 09:53:29',
                'updated_at' => '2026-08-26 08:58:39',
            ],
            [
                'id' => 95,
                'username' => 'test_dirut',
                'full_name' => 'Dirut Test',
                'email' => 'pbl.512hebat+test_dirut@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$J0Y61OB2RxL3iMEQV.94AuvCrFp93GAHxpemh6sC82dEud3KGHunW',
                'role' => 'Direktur Utama',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-08-18 09:53:29',
                'updated_at' => '2026-08-26 08:58:39',
            ],
            [
                'id' => 96,
                'username' => 'budi_qms',
                'full_name' => 'Budi Santoso (QMS)',
                'email' => 'pbl.512hebat+budi_qms@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$L17G8VBCpRTJI4cxa4mYEeO9HwUtX9irzlATaePXEKkuxjUI/TqlO',
                'role' => 'Ka. Dept. QMS',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'HPlifRZ0RzRe0QU90fqrfQM7ElTr5wvHZOP4T5hnqFs546hqw6yDijz1FtTn',
                'created_at' => '2026-08-18 09:55:45',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 98,
                'username' => 'hendra_dirut',
                'full_name' => 'H. Hendra (Dirut)',
                'email' => 'pbl.512hebat+hendra_dirut@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$hsiwxsJhkGQS.mCXHIe48ud/6/uxzk5GxGvLsXE6WPu7YqYljwKzq',
                'role' => 'Direktur Utama',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-08-18 09:55:45',
                'updated_at' => '2026-08-26 08:58:39',
            ],
            [
                'id' => 164,
                'username' => 'hanifabyad',
                'full_name' => 'Muhammad Hanif',
                'email' => 'pbl.512hebat+hanifabyad@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$w5LLJgO84feTFgDprWvoWekXdQkuhzGrIHhN9Q6PLPdoUE5Bt110G',
                'role' => 'Chief F & A Inmarr',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => '8FkRBmrk1jZtNMjIOchQXWi6ilS6VWYMEG01gBIyFTshY1yXUZ8uAZoxbdqB',
                'created_at' => '2026-08-20 07:22:58',
                'updated_at' => '2026-08-26 08:58:39',
            ],
            [
                'id' => 199,
                'username' => 'hendro',
                'full_name' => 'Hendro Suwarsono',
                'email' => 'pbl.512hebat+hendro@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$aKkoGavUXEV3.gmc32UV2O9c.f6nG9PKE7BV7cU4YDyfIN4.WAmDS',
                'role' => 'Ka. BU CPT',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => '8KMxKvHLky570Iqsoz4Zij7yC86mu1xIllSKRKM1vl2aP0hmpl2QsSMWrbqZ',
                'created_at' => '2026-08-24 14:27:09',
                'updated_at' => '2026-08-27 10:38:43',
            ],
            [
                'id' => 246,
                'username' => 'hendro_dir',
                'full_name' => 'Hendro Suwarsono',
                'email' => 'pbl.512hebat+hendro_dir@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$vTFTeputHMGTfK0iz.PjWOMvZ10DlXf/EvpN5GeVDcbmm8ry7LPfu',
                'role' => 'Direktur CPT',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'TkTrImRh3d072302xr245QOcwlF4bs6Pe96ySOFzWYqdRUfCa32YTBUxuE94',
                'created_at' => '2026-08-26 09:43:53',
                'updated_at' => '2026-08-26 09:43:53',
            ],
            [
                'id' => 365,
                'username' => 'dirut',
                'full_name' => 'Hendra Wijaya, S.E., M.M.',
                'email' => 'dirut@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$u9qHxxwlLdF4vu.ap9AdFOEPDvDi6wXZLA/dkl1nIZT9v/u0.PULO',
                'role' => 'Direktur Utama',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:46',
                'updated_at' => '2026-09-01 08:34:46',
            ],
            [
                'id' => 366,
                'username' => 'kadiv_retail',
                'full_name' => 'Agus Setiawan, S.T.',
                'email' => 'kadiv.retail@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$1ISsTVAFsyjxcByXXrEh8eT5bg4CGK0zScKdIZwHr3IhV3jss58yO',
                'role' => 'Ka. Div Retail',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:46',
                'updated_at' => '2026-09-01 08:34:46',
            ],
            [
                'id' => 367,
                'username' => 'chief_fa',
                'full_name' => 'Linda Permata, S.E., Ak.',
                'email' => 'chief.fa@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$VIBgLcWvpIN1sM8M6P87P.3A4r3KzmjPSWNo4kPz25Ww75dpAOoxS',
                'role' => 'Chief F&A Holding',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:47',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 368,
                'username' => 'ka_qms',
                'full_name' => 'Trinwetty, S.Si.',
                'email' => 'qms@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$W2im7vdEtzNOD0QbvYbWNuDtx/V7alr0p/qcdYld.jQZN1dYXZd1S',
                'role' => 'Ka. Dept. QMS',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:47',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 369,
                'username' => 'ka_it',
                'full_name' => 'Rian Pratama, S.Kom.',
                'email' => 'it@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$Ui7V14L2PX6tT2VUSHrKXe7fPCnwHGpjQGccSe6Ah1lGt6eEh42lK',
                'role' => 'Ka. Dept. IT',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:47',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 370,
                'username' => 'ka_hc',
                'full_name' => 'Maya Kartika, S.Psi.',
                'email' => 'hc@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$MlC9i0s93HHmVSfMFitIBe0ZhGqk7S.1RcEcPuW849mXv7UNXmvDK',
                'role' => 'Ka. Dept. HC',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => 'mOtKbK3rIfg6WgnDDh2x8hwUhj4I8hWbnplbDtGoYUtJbkZZDU0t8aBqcAip',
                'created_at' => '2026-09-01 08:34:47',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 371,
                'username' => 'ka_hse',
                'full_name' => 'Bambang Sutrisno, S.K.M.',
                'email' => 'hse@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$kYdNwS1JeX/NX8alPDrsLu71msHnQHiOFdkQ7B.Y3UUHIDr2Bji3q',
                'role' => 'Ka. Dept. HSE',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:47',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 372,
                'username' => 'ka_spbu',
                'full_name' => 'Dedi Supriyadi',
                'email' => 'spbu@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$xUGTsmO6iBO8jdWrVv8NuebhjwCdxnk/YN7ZQCCX5i5Yyia1yjY/i',
                'role' => 'Ka. BU SPBU',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:48',
                'updated_at' => '2026-09-01 08:34:48',
            ],
            [
                'id' => 373,
                'username' => 'ka_gas',
                'full_name' => 'Fajar Nugroho, S.T.',
                'email' => 'gas@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$eLuTVoJUCAvrtDfjBcMdqOQcDfWdT0o7OrqzNASFtOs0vK4.eQ/LK',
                'role' => 'Ka. BU Gas & SPBE',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:48',
                'updated_at' => '2026-09-01 08:34:48',
            ],
            [
                'id' => 374,
                'username' => 'ka_inmar',
                'full_name' => 'Capt. Surya Dharma, M.Mar.',
                'email' => 'inmar@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$onwvaODF2/cOPoCYf28rk.kYFjTZBrK4/zpHfcXZUMIHObMQnHYBi',
                'role' => 'Ka. BU Inmarr',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:48',
                'updated_at' => '2026-09-01 08:34:48',
            ],
            [
                'id' => 375,
                'username' => 'ka_cpt',
                'full_name' => 'Ir. Arif Hidayat',
                'email' => 'cpt@pkmgroup.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$rBxOmAzEmxqm6h/XmBsOOezGxkqfaFBjvB.owbwMZK.QthFOSVkM.',
                'role' => 'Ka. BU CPT',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-01 08:34:48',
                'updated_at' => '2026-09-01 08:34:48',
            ],
            [
                'id' => 630,
                'username' => 'wendifadila',
                'full_name' => 'Wendi Fadila Indri',
                'email' => 'wendi@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$YtQBP/dFutcWDmLbZoDFcedY8LYuqLZPxXm/IpxzczRIA2A363MjC',
                'role' => 'Ka. Operasional SPBU',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:39',
                'updated_at' => '2026-09-08 16:13:39',
            ],
            [
                'id' => 631,
                'username' => 'teddy',
                'full_name' => 'Teddy',
                'email' => 'teddyvvoo@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$pFgzmSZJQymBONLH5yNrDeep0OfDOiNW19YnSJN2NVSQJw3Fl4Jbm',
                'role' => 'Ka. Operasional BBM Retail',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:40',
                'updated_at' => '2026-09-08 16:13:40',
            ],
            [
                'id' => 632,
                'username' => 'lusman',
                'full_name' => 'Lusman Gustaman',
                'email' => 'lusman.gustaman@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$c6yfbagJJjg2EFA.naRh6Ogz3NZoyXKsyy344qUzpcLgr/XSuttWq',
                'role' => 'Koordinator Sales & Marketing',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:40',
                'updated_at' => '2026-09-08 16:13:40',
            ],
            [
                'id' => 633,
                'username' => 'sriwarsana',
                'full_name' => 'Sri Warsana',
                'email' => 'ka-ops.pksp@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$eq3CGE1mG1akupsXe5bj1.X2nH74uvb0kXmUHe95AWHoqRDZy2Rc6',
                'role' => 'Ka. Cab TBK',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:40',
                'updated_at' => '2026-09-08 16:13:40',
            ],
            [
                'id' => 634,
                'username' => 'yusri',
                'full_name' => 'Yusri',
                'email' => 'yusri@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$8g6nFr5oic3VCs104kkBh.DGy.g/oN/D/PyJTMSEpGRhy8KltHw.q',
                'role' => 'Ka. Cab Guntung',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:40',
                'updated_at' => '2026-09-08 16:13:40',
            ],
            [
                'id' => 635,
                'username' => 'wendijatmiko',
                'full_name' => 'Wendi Jatmiko',
                'email' => 'wendi.jatmiko@pkmretail.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$tdgqIZeFRzuTOyRo/78iw.48jTT5IGAlPPXu98.lddfvyj5S9azPi',
                'role' => 'Ka. Cab TPI',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:41',
                'updated_at' => '2026-09-08 16:13:41',
            ],
            [
                'id' => 636,
                'username' => 'imanhelmi',
                'full_name' => 'Iman Helmi Ardani',
                'email' => 'iman.helmi@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$fYska6SKJYLcVg0CallIvO59jBIgCrTipREhvt9vZKUAFrAWix/UC',
                'role' => 'Ka. Jakarta',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:41',
                'updated_at' => '2026-09-08 16:13:41',
            ],
            [
                'id' => 637,
                'username' => 'jakapamungkas',
                'full_name' => 'Jaka Pamungkas',
                'email' => 'ka-ops.gas@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$YaWxcXtNjWhHOKp5GEgtGuulYZrpZU5S6KotjdbHak85xYidiLyvy',
                'role' => 'Ka. Operasional Batam',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:41',
                'updated_at' => '2026-09-08 16:13:41',
            ],
            [
                'id' => 638,
                'username' => 'adityawisnu',
                'full_name' => 'Aditya Wisnu',
                'email' => 'aditya@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$wEnBvBTxIfg8k5vW8hyQduIQEsN0fKEjSlGqtJhK6y9YKp6xO0g3.',
                'role' => 'Ka. BU Inmarr',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:41',
                'updated_at' => '2026-09-08 16:13:41',
            ],
            [
                'id' => 639,
                'username' => 'suseno',
                'full_name' => 'Suseno Seno',
                'email' => 'suseno@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$FAS4lz5tWO9LL436LqIxYeZZwrP9HEFItYp5a3J/TrLwaEXHmZmLe',
                'role' => 'Chief F & A Inmarr',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:41',
                'updated_at' => '2026-09-08 16:13:41',
            ],
            [
                'id' => 640,
                'username' => 'erwan',
                'full_name' => 'Erwan',
                'email' => 'ka-ops.cngm@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$1g9j3aE/ONJgy.y4j70cjepnH6BDzGFyj28SYROheP8SBYLWOtxXm',
                'role' => 'Ka. Operasional Inmarr',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:42',
                'updated_at' => '2026-09-08 16:13:42',
            ],
            [
                'id' => 641,
                'username' => 'rahmatsidikhi',
                'full_name' => 'Rahmat Sidikhi',
                'email' => 'kasie.ga@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$ehF0avNTYsiggu3.IXQAu.RnNPj999aVCV8SeWvaOEgdM7P3w0Tam',
                'role' => 'Legal & HC Manager',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:42',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 642,
                'username' => 'indrajat',
                'full_name' => 'Indrajat',
                'email' => 'indrajat@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$W7MhNcSbG0XPh0phwyNih.JSU92y9hxAJI9iQxXieTxFnv144m2Ka',
                'role' => 'Marine Superintendent',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:42',
                'updated_at' => '2026-09-08 16:13:42',
            ],
            [
                'id' => 643,
                'username' => 'handika',
                'full_name' => 'Handika',
                'email' => 'handika@pkmgroup.co.id',
                'whatsapp_number' => null,
                'password' => '$2y$12$VPrUveUMJ/vNyUo8SCU8x.fabzhyQvlpI1uyFz4PwceksmulcNS/.',
                'role' => 'Ka. Operasional CPT',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:13:42',
                'updated_at' => '2026-09-09 08:34:06',
            ],
            [
                'id' => 645,
                'username' => 'Hanif',
                'full_name' => 'Muhammad Hanif',
                'email' => 'abyadhanif2@gmail.com',
                'whatsapp_number' => null,
                'password' => '$2y$12$4cNI5FsVibpp/ZU3chwKeOrbnNQDzI5Du5z97aL7DacGm2Y4V75He',
                'role' => 'Karyawan QMS',
                'can_manage_cpt_contracts' => 0,
                'signature' => null,
                'status' => 1,
                'remember_token' => null,
                'created_at' => '2026-09-08 16:19:42',
                'updated_at' => '2026-09-09 08:34:06',
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->updateOrInsert(
                ['id' => $user['id']],
                $user
            );
        }
    }
}
